version: "3"
services:
  web:
    # Pull the image we uploaded in step 2 from the registry.
    image: lymbo49/spring-rest-api:application
    # Run 5 instances of that image as a service called web, limiting each one to use, at most, 50% of a single core of CPU time and 50MB of RAM.
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.5"
          memory: 50M
      restart_policy:
        #Immediately restart containers if one fails.
        condition: on-failure
    ports:
      # Map port 8000 on the host to web’s port 8080.
      - "8000:8080"
    networks:
      #Instruct web’s containers to share port 80 via a load-balanced network called webnet. (Internally, the containers themselves publish to web’s port 80 at an ephemeral port.)
      - webnet

# Define the webnet network with the default settings (which is a load-balanced overlay network).
networks:
  webnet: